# SPDX-FileCopyrightText: 2025 Juan Manuel Méndez Rey
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  conquer:
    build:
      context: ./conquer
    container_name: conquer-production
    environment:
      - TTYD_USERNAME=${TTYD_USERNAME:-conquer}
      - TTYD_PASSWORD=${TTYD_PASSWORD:-game2024secure}
      - MAX_CLIENTS=${MAX_CLIENTS:-5}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-1800}
    restart: unless-stopped
    networks:
      - conquer-production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  apache:
    build: ./apache
    container_name: apache-production
    volumes:
      # Let's Encrypt certificates
      - ./apache/certs/live/conquer.vejeta.com:/usr/local/apache2/conf/certs/live/conquer.vejeta.com:ro
      # Production Apache configuration
      - ./apache/production.conf:/usr/local/apache2/conf/extra/httpd-proxy.conf:ro
      # Let's Encrypt webroot for certificate challenges
      - ./apache/certs/webroot:/var/lib/letsencrypt:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - conquer
    restart: unless-stopped
    networks:
      - conquer-production

  certbot:
    image: certbot/certbot
    container_name: certbot-production
    volumes:
      - ./apache/certs:/etc/letsencrypt:rw
      - ./apache/certs:/var/lib/letsencrypt:rw
      - ./apache/certs/webroot:/var/lib/letsencrypt:rw
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    networks:
      - conquer-production

networks:
  conquer-production:
    driver: bridge