#!/bin/bash
# SPDX-FileCopyrightText: 2025 Juan Manuel Méndez Rey
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Build Conquer for the browser (WebAssembly, Emscripten): the game
# (conquer) and the turn update (conqrun), for web/try/.
#
# Usage: wasm/build.sh [CONQUER_SOURCES]
#   CONQUER_SOURCES: the gpl-release directory of the game sources, with
#   conquer/patches applied (default: clone and patch into a temp dir).
# Needs emcc (https://emscripten.org) in PATH.

set -e

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$HERE")"
OUT="$ROOT/web/try"
SRC="${1:-}"

if [ -z "$SRC" ]; then
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT
    git clone -q "${CONQUER_REPO:-https://github.com/vejeta/conquer.git}" "$tmp/conquer"
    for p in "$ROOT"/conquer/patches/*.patch; do
        git -C "$tmp/conquer" apply --whitespace=nowarn --check "$p" 2>/dev/null &&
            git -C "$tmp/conquer" apply --whitespace=nowarn "$p"
    done
    SRC="$tmp/conquer/gpl-release"
fi

BUILD=$(mktemp -d)
# A copy of the sources: they declare "long time();", which clashes with
# the 64-bit time_t of WebAssembly. Every call passes a null pointer or
# assigns the result, so dropping the old declarations is enough.
cp -r "$SRC" "$BUILD/src"
sed -i 's/^[[:space:]]*long[[:space:]]\+time();//' "$BUILD/src"/*.c
SRC="$BUILD/src"
CFLAGS=(-O2 -std=gnu99 -w -Wno-incompatible-pointer-types -Wno-int-conversion
    -Wno-implicit-function-declaration -D_GNU_SOURCE -D_DEFAULT_SOURCE
    -DDEFAULTDIR=\"/conquer/lib\" -DEXEDIR=\"/conquer/bin\"
    -DVERSION=\"4\" -DPATCHLEVEL=\"12\" -DLOGIN=\"conquer\"
    -I"$HERE/shim" -include "$HERE/shim/shim.h" -I"$SRC")

# Same objects as the game's Makefile: sources shared by both programs are
# built twice, with -DCONQUER (game) or -DADMIN (conqrun)
BOTH="combat admin makeworl spew newlogin update npc randeven check commands forms main move reports display extcmds"
GAME="commands cexecute:G forms io:G main move navy:G magic:G misc:G reports data:G display extcmds trade:G check"
ADMIN="combat cexecute:A io:A admin makeworl navy:A spew newlogin update magic:A npc misc:A randeven data:A trade:A check"

compile() {   # compile <list> <suffix>
    local objs=() item src kind flags
    for item in $1; do
        src=${item%%:*}
        kind=${item#*:}
        [ "$kind" = "$item" ] && kind=both
        case "$kind" in
            G) flags=(-DCONQUER) ;;
            A) flags=(-DADMIN) ;;
            *) flags=(-DADMIN -DCONQUER) ;;
        esac
        emcc "${CFLAGS[@]}" "${flags[@]}" -c "$SRC/$src.c" -o "$BUILD/$src.$kind.$2.o"
        objs+=("$BUILD/$src.$kind.$2.o")
    done
    emcc "${CFLAGS[@]}" -c "$HERE/shim/shim.c" -o "$BUILD/shim.$2.o"
    objs+=("$BUILD/shim.$2.o")
    echo "${objs[@]}"
}

LDFLAGS=(-O2 -sASYNCIFY -sASYNCIFY_STACK_SIZE=65536 -sFORCE_FILESYSTEM -lidbfs.js
    -sMODULARIZE=1 -sINVOKE_RUN=0 -sEXIT_RUNTIME=1 -sALLOW_MEMORY_GROWTH=1
    -sENVIRONMENT=web -sEXPORTED_RUNTIME_METHODS=callMain,FS,IDBFS)

mkdir -p "$OUT"
read -r -a game_objs <<< "$(compile "$GAME" game)"
emcc "${game_objs[@]}" "${LDFLAGS[@]}" -sEXPORT_NAME=createConquer -o "$OUT/conquer.js"
read -r -a admin_objs <<< "$(compile "$ADMIN" admin)"
emcc "${admin_objs[@]}" "${LDFLAGS[@]}" -sEXPORT_NAME=createConqrun -o "$OUT/conqrun.js"

# The practice world, written by conqrun itself (compiled for Node with
# direct file access), so its data layout is the one of the browser build.
# The world generator reads the computer nations from the compiled-in
# directory, /conquer/lib.
emcc "${admin_objs[@]}" "${LDFLAGS[@]/-sENVIRONMENT=web/-sENVIRONMENT=node}" -sNODERAWFS=1 \
    -sEXPORT_NAME=createConqrun -o "$BUILD/conqrun-node.js"
world="$BUILD/world"
mkdir -p "$world" /conquer/lib
cp "$SRC/nations" "$SRC"/help[0-5] /conquer/lib/ 2>/dev/null || true
# The help files are generated by a native build of the game
[ -f "$SRC/help0" ] || make -s -C "$SRC" > /dev/null
cp "$SRC/nations" "$SRC"/help[0-5] /conquer/lib/
cp "$SRC"/help[0-5] "$SRC/rules" "$world"/
if ! node "$HERE/make-world.js" "$BUILD/conqrun-node.js" "$world" > "$BUILD/make-world.log"; then
    tail -c 3000 "$BUILD/make-world.log" | sed 's/\x1b\[[0-9;?]*[A-Za-z]/ /g'
    exit 1
fi
rm -rf "$OUT/world"
mkdir -p "$OUT/world"
cp "$world"/* "$OUT/world/"
chmod 644 "$OUT"/world/* "$OUT"/*.js "$OUT"/*.wasm
# The page loads the files listed here into the browser's storage
(cd "$OUT/world" && printf '%s\n' * | awk 'BEGIN { printf "[" } { printf "%s\"%s\"", (NR > 1 ? "," : ""), $0 } END { print "]" }') > "$OUT/world/files.json"
rm -rf "$BUILD"
ls -la "$OUT"/conquer.* "$OUT"/conqrun.* "$OUT/world"
